[profile.default]
src = 'contracts/src'
out = 'out'
libs = ['lib', 'node_modules']
remappings = ["account-abstraction/=lib/account-abstraction/"]
test = 'contracts/test'
cache = true
cache_path = 'cache'
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
line_length = 120

[rpc_endpoints]
sepolia = "https://sepolia.base.org"
base_sepolia = "https://sepolia.base.org"
mainnet = "https://mainnet.base.org"

[etherscan]
base = { key = "${ETHERSCAN_API_KEY}" }
base_sepolia = { key = "${ETHERSCAN_API_KEY}" }

# Testing configuration
[fuzz]
runs = 256

# Solidity compiler configuration
solc_version = "0.8.23"
evm_version = "shanghai"
optimizer = true
optimizer_runs = 200
extra_output = ["metadata"]
extra_output_files = ["metadata"]